@API_HostAddress = https://localhost:44319

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{API_HostAddress}}/api/values

###

POST {{API_HostAddress}}/api/Person/AddPerson
Content-Type: application/json

{
  
 

}

###
